# Build Stage
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
# 'npm ci' is faster and stricter than 'npm install' (great for CI/CD)
RUN npm ci 
COPY . .
RUN npm run build

# Production Stage
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
# Install ONLY production dependencies
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
# Copy Prisma schema for generating client
COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "start"]